### ISSUE TITLE
Request for code for generating novel sequences

### ISSUE THREAD

**Issue by CTDancer** [OpenProteinAI/PoET#1]
Thank you for your brilliant work!

I'm wondering whether the code for generating novel sequences within a protein family will be released. 

Thank you,
Tong

**Comment by timt51** [comment]
Thanks for the compliment! This response is super late but in case it's useful -

We're not planning on updating the repo any time soon with an example of generation, but [this method](https://github.com/OpenProteinAI/PoET/blob/9b2239be84ee39691ec6ad4184925156f2ac332f/poet/models/poet.py#L898) should work. `xs` and `segment_sizes` mean the same thing as the corresponding parameters of the [embed method](https://github.com/OpenProteinAI/PoET/blob/9b2239be84ee39691ec6ad4184925156f2ac332f/poet/models/poet.py#L731) used in the [scoring script](https://github.com/OpenProteinAI/PoET/blob/9b2239be84ee39691ec6ad4184925156f2ac332f/scripts/score.py#L175).

**Comment by CTDancer** [comment]
Thank you! I will try this method.
